test/python/mock/test_mock_module_deprecation.py:26:51: F811 Redefinition of unused `FakeWashington` from line 24
test/python/mock/test_mock_module_deprecation.py:28:62: F811 Redefinition of unused `FakeWashington` from line 26
test/python/mock/test_mock_module_deprecation.py:28:62: F401 [*] `qiskit.test.mock.backends.washington.FakeWashington` imported but unused