Oxidize classical expression use in Rust code. (#14176)
* s

* Rename BitData to ObjectRegistry.

* s

* Update tests for new error string.

This is only really a user-facing error message when
working with DAGCircuit, since QuantumCircuit first
checks if the bits being added to it are duplicates.
And, in the case of DAGCircuit, the previous error
message was already unfriendly:

ValueError: Existing bit ShareableQubit(Owned { register: OwningRegisterInfo { name: "q16", size: 2, subclass: QUBIT }, index: 0 }) cannot be re-added in strict mode.

* Fix comment in commutation checker.

* Fix lint.

* Address review comments.

* Unify identifier handling in DAG.

Tracks stretches the same way we track vars.
Also happens to fix a bug in DAG equality where
order mattered between stretch captures (it should
never have). And, fixes a serialization bug with
stretches.

* Fix tests.

* Improve testing and fix bug.

* Add pickle and deepcopy tests for stretches.

Also fix lint.

* Initial commit.

* Implement types.

* Wire-up Rust-based Types.

* Add more plumbing for Expr.

* Expose Op enums.

* WIP

* WIP

* Test passing.

* Refactor module organization.

* Fix clippy.

* Downcast instead of extract.

* Fix merge.

* Undo breaking name change.

* Add release note.

* Fix lint.

* Fix Python lint.

* Add missing documentation, fix opcode docs.

* Impl repr for expressions.

* Fix pickling for facade enums.

* Manually revert DAGCircuit changes.

I'll do these in a separate PR.

* Revert "Manually revert DAGCircuit changes."

This reverts commit 35938ec0699745e3bd9dff5b952cba84e2726f7f.

* WIP

* Pass 1.

* Use identifier_info for copy_empty_like.

* Convert to expr during creation of QuantumCircuitData.

* Remove Python token need for Var and Stretch.

* Use sets for vars. Whoops!

* Fix lint.

* Use fast-rng feature for uuid.

* Fix merge, further oxidize compose.

* Updates after merge.

* Address review comments.