Unify identifer handling of `Var` and `Stretch` in `DAGCircuit` (#14000)
* s

* Rename BitData to ObjectRegistry.

* s

* Update tests for new error string.

This is only really a user-facing error message when
working with DAGCircuit, since QuantumCircuit first
checks if the bits being added to it are duplicates.
And, in the case of DAGCircuit, the previous error
message was already unfriendly:

ValueError: Existing bit ShareableQubit(Owned { register: OwningRegisterInfo { name: "q16", size: 2, subclass: QUBIT }, index: 0 }) cannot be re-added in strict mode.

* Fix comment in commutation checker.

* Fix lint.

* Address review comments.

* Unify identifier handling in DAG.

Tracks stretches the same way we track vars.
Also happens to fix a bug in DAG equality where
order mattered between stretch captures (it should
never have). And, fixes a serialization bug with
stretches.

* Fix tests.

* Improve testing and fix bug.

* Add pickle and deepcopy tests for stretches.

Also fix lint.

* Undo breaking name change.

* Add release note.

* Fix lint.

* Fix Python lint.

* Address review comments.