fixed quotes in README.md (#14281) (#14285)
prior, quotes around `"meas"` in the README.md file were not escaped properly, leading to the following error when running the code

```shell
...
    print(f" > Counts: {result[0].data["meas"].get_counts()}")
                                        ^^^^
SyntaxError: f-string: unmatched '['
```

changed quotes to single quotes (that don't need to be escaped)

versions:
* python 3.10
* qiskit 2.0.0

(cherry picked from commit 9b660772a4e403f3311b3315e9020b552ac74a32)

Co-authored-by: ClaytonNorthey92 <clayton.northey@gmail.com>